import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.contenedor_fotografia}></div>
        <div className={styles.marco}> 
          {children}
          <footer className={styles.footer}>
            <p className={styles.footer_p}>Con la tecnología de nextjs</p>
            <h5 className={styles.footer_h5}>Imágenes del tema: <span>Michael Elkan</span> </h5>
          </footer>
        </div>
      </body>
    </html>
  );
}
